# version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    # env_file:
    #   - .env
    #   - .env.example
    # command: "npm install" 
    volumes:
      - ./src:/app/src