#バージョン20以上だとnpm run dev時に警告が出る
FROM node:23-alpine3.19
WORKDIR /app
COPY ./package.json /app/package.json
RUN npm install
RUN npx -y prisma generate
COPY . /app
# RUN npx prisma migrate dev
CMD [ "npm", "run", "dev" ]
