name: Build and Deploy 

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "Dockerfile"
      - "Dockerfile.*"

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    #　workflow内での環境変数をセット
    env:
      DOCKER_USERNAME: potekichi
      PROJECT_NAME: learning-path

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{env.DOCKER_USERNAME}}/${{ env.PROJECT_NAME }}:${{ github.run_id }}
            ${{env.DOCKER_USERNAME}}/${{ env.PROJECT_NAME }}:latest
          file: ./Dockerfile.standalone
          context: .
          platforms: linux/amd64
          build-args: |
            DATABASE_URL=${{secrets.DATABASE_URL}}
            NEXT_PUBLIC_SUPABASE_URL=${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
            BASE_URL=${{secrets.BASE_URL}}

  update-kubernetes-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
